// 35 Phillips — project data
window.PROJECT = {
  address: "35 Phillips Rd",
  city: "Newton, NJ 07860 (Green Twp)",
  sqft: 0,
  floors: 1,
  beds: 4,
  baths: "3",
  started: "July 1, 2026",
  target: "Sept 14, 2026",
  budget: "$ -- confidential --",
  permitNo: "BLD-####",
};

// Phase definitions in order
window.PHASES = [
  {
    id: "gasrun",
    num: "01",
    name: "Gas Run",
    short: "Gas Run",
    trade: "Plumbing / Gas",
    duration: 3,
    contractor: "TBD",
    lead: "TBD",
    phone: "TBD",
    areas: ["Gas service from street", "Meter location", "Trenching"],
    milestones: [
      { label: "Utility locate (Dig Safe)", done: false },
      { label: "Trench from main to house", done: false },
      { label: "Gas line run", done: false },
      { label: "Meter install (utility)", done: false },
      { label: "Pressure test", done: false },
    ],
    notes: "Unblocks the entire project — meter must be set before any rough-in work. 2-week utility lead time on meter install.",
  },
  {
    id: "eval",
    num: "02",
    name: "Site Evaluation",
    short: "Eval",
    trade: "General / Architect",
    duration: 6,      // days
    contractor: "Haskell + Co. Architects",
    lead: "M. Haskell, AIA",
    phone: "978-555-0142",
    areas: ["Whole house", "Exterior envelope", "Foundation"],
    milestones: [
      { label: "Structural walkthrough", done: false },
      { label: "Measured drawings", done: false },
      { label: "Existing conditions report", done: false },
      { label: "Scope of work finalized", done: false },
    ],
    notes: "Load-bearing wall between kitchen & dining confirmed. Chimney flue condemned — must be removed in demo.",
  },
  {
    id: "bids",
    num: "03",
    name: "Bids & Proposals",
    short: "Bids",
    trade: "Owner / GC",
    duration: 9,
    contractor: "Owner-managed",
    lead: "You",
    phone: "—",
    areas: ["All trades"],
    milestones: [
      { label: "Demo bids (3)", done: false },
      { label: "Framing bids (3)", done: false },
      { label: "HVAC / plumbing bids (4)", done: false },
      { label: "Electrical bids (3)", done: false },
      { label: "Contracts signed", done: false },
    ],
    notes: "All contracts countersigned. Lien waivers on file.",
  },
  {
    id: "permits",
    num: "04",
    name: "Permits",
    short: "Permits",
    trade: "Owner / GC",
    duration: 14,
    contractor: "Owner-managed",
    lead: "You",
    phone: "—",
    areas: ["Whole house"],
    milestones: [
      { label: "Building permit application submitted", done: false },
      { label: "Permit fee paid", done: false },
      { label: "Building permit approved", done: false },
      { label: "Electrical permit approved", done: false },
      { label: "Plumbing / gas permit approved", done: false },
      { label: "Permit posted on site", done: false },
    ],
    notes: "Must be approved before any work begins. Green Twp. building dept. — allow 2–4 week review window.",
  },
  {
    id: "order",
    num: "05",
    name: "Order Material",
    short: "Order",
    trade: "Procurement",
    duration: 6,
    contractor: "Owner-managed",
    lead: "You",
    phone: "—",
    areas: ["Long-lead items"],
    milestones: [
      { label: "Windows & doors ordered", done: false },
      { label: "HVAC equipment ordered", done: false },
      { label: "Cabinets & counters ordered", done: false },
      { label: "Finish fixtures staged", done: false },
    ],
    notes: "Long-lead procurement. Windows 12-week lead, cabinets 8–10 weeks.",
  },
  {
    id: "demo",
    num: "06",
    name: "Demolition",
    short: "Demo",
    trade: "Demo",
    duration: 4,
    contractor: "Coogan Demo & Haul",
    lead: "Rick Coogan",
    phone: "978-555-0188",
    areas: ["Kitchen", "Dining", "1st-floor bath", "Primary bath", "Chimney stack"],
    milestones: [
      { label: "Asbestos test / clearance", done: false },
      { label: "Interior walls out", done: false },
      { label: "Chimney removed to roofline", done: false },
      { label: "Debris hauled, site broom-clean", done: false },
      { label: "Sign-off walkthrough", done: false },
    ],
    notes: "Original 1908 shiplap preserved in a stack in the garage — owner request.",
  },
  {
    id: "framing",
    num: "07",
    name: "Framing",
    short: "Framing",
    trade: "Carpentry",
    duration: 8,
    contractor: "Mallon",
    lead: "J. Mallon",
    phone: "###-###-####",
    areas: ["FL-02", "Foyer", "Rear dormer", "New stair opening"],
    milestones: [
      { label: "LVL beam over kitchen set", done: false },
      { label: "Primary suite walls up", done: false },
      { label: "Rear dormer framed", done: false },
      { label: "Stair rough opening", done: false },
      { label: "Framing inspection", done: false },
    ],
    notes: "LVL spec changed from 14\" to 16\" per structural. Awaiting lumber delivery Thu.",
  },
  {
    id: "masonry",
    num: "08",
    name: "Masonry",
    short: "Masonry",
    trade: "Masonry",
    duration: 3,
    contractor: "TBD",
    lead: "TBD",
    phone: "TBD",
    areas: ["Foundation repairs", "Front steps rebuild", "New patio footing"],
    milestones: [
      { label: "Foundation crack injection", done: false },
      { label: "Front steps rebuild", done: false },
      { label: "Patio footing pour", done: false },
    ],
    notes: "Scheduled to overlap with framing — foundation work only while framers are upstairs.",
  },
  {
    id: "roofing",
    num: "09",
    name: "Roofing / Siding / Gutters",
    short: "Roof+",
    trade: "Roofing / Exterior",
    duration: 5,
    contractor: "TBD",
    lead: "TBD",
    phone: "TBD",
    areas: ["Main roof", "Rear dormer", "Porch roof", "Full siding", "Gutters + downspouts"],
    milestones: [
      { label: "Roof tear-off", done: false },
      { label: "Ice & water + underlayment", done: false },
      { label: "Architectural shingles", done: false },
      { label: "Flashing + step flashing", done: false },
      { label: "Siding install", done: false },
      { label: "Gutters + downspouts", done: false },
    ],
    notes: "Must happen after dormer framing, before finish. Weather-dependent. Siding + gutters rolled into this phase to keep the exterior crew continuous.",
  },
  {
    id: "trim",
    num: "10",
    name: "Fascia / Soffit / Trim",
    short: "Trim",
    trade: "Exterior Carpentry",
    duration: 3,
    contractor: "TBD",
    lead: "TBD",
    phone: "TBD",
    areas: ["Fascia boards", "Soffits + ventilation", "Corner boards", "Window + door trim"],
    milestones: [
      { label: "Fascia install", done: false },
      { label: "Soffit + vent install", done: false },
      { label: "Corner boards", done: false },
      { label: "Window + door trim", done: false },
      { label: "Caulk + paint prep", done: false },
    ],
    notes: "Runs alongside siding. Drives the exterior finish look — locks in paint-ready state.",
  },
  {
    id: "windows",
    num: "11",
    name: "Windows & Doors",
    short: "W+D",
    trade: "Carpentry",
    duration: 2,
    contractor: "Mallon",
    lead: "J. Mallon",
    phone: "###-###-####",
    areas: ["22 windows", "Front door", "Rear slider", "Interior doors (12)"],
    milestones: [
      { label: "Window delivery", done: false },
      { label: "Exterior units set", done: false },
      { label: "Flashing + tape", done: false },
      { label: "Interior pre-hung", done: false },
    ],
    notes: "Marvin Elevate, black exterior / stained interior. 12-week lead time — already ordered.",
  },
  {
    id: "hvac",
    num: "12",
    name: "AC / Heat",
    short: "HVAC",
    trade: "TBD",
    duration: 4,
    contractor: "TBD",
    lead: "TBD",
    phone: "TBD",
    areas: ["Whole house HVAC", "Ductwork", "Mini-splits"],
    milestones: [
      { label: "Equipment delivery", done: false },
      { label: "Ductwork rough", done: false },
      { label: "Mini-split line sets", done: false },
      { label: "Rough inspection", done: false },
    ],
    notes: "Coordinated with electrical — shared chases in kitchen soffit.",
  },
  {
    id: "gas",
    num: "13",
    name: "Gas / Heat",
    short: "Gas",
    trade: "Plumbing / Gas",
    duration: 3,
    contractor: "Dalton Mechanical",
    lead: "K. Dalton",
    phone: "978-555-0620",
    areas: ["Gas service", "Boiler", "Water heater"],
    milestones: [
      { label: "Gas line from street", done: false },
      { label: "Meter install (utility)", done: false },
      { label: "Boiler + indirect water heater", done: false },
      { label: "Plumbing rough", done: false },
      { label: "Rough inspection", done: false },
    ],
    notes: "Oil → gas conversion. Utility meter install requires 2-week lead.",
  },
  {
    id: "electric",
    num: "14",
    name: "Electrical",
    short: "Elec",
    trade: "Electrical",
    duration: 5,
    contractor: "Voltage Bros.",
    lead: "R. Voltaggio",
    phone: "617-555-0708",
    areas: ["200A service upgrade", "Whole-house rewire", "Low-voltage / data"],
    milestones: [
      { label: "Service upgrade", done: false },
      { label: "Rough-in", done: false },
      { label: "Rough inspection", done: false },
      { label: "Trim out", done: false },
      { label: "Final inspection", done: false },
    ],
    notes: "Rough must precede insulation. Trim happens after paint.",
  },
  {
    id: "insulation",
    num: "15",
    name: "Spray Foam Insulation",
    short: "Insul.",
    trade: "Insulation",
    duration: 2,
    contractor: "AllJersey Spray Foam LLC",
    lead: "A. Oduya",
    phone: "862-237-5519",
    areas: ["Roof deck (closed cell)", "Exterior walls (open cell)", "Rim joists"],
    milestones: [
      { label: "Rough-ins complete (prereq)", done: false },
      { label: "Closed-cell roof deck", done: false },
      { label: "Open-cell walls", done: false },
      { label: "Insulation inspection", done: false },
    ],
    notes: "Cannot start until HVAC, plumbing, electrical rough-ins pass inspection.",
  },
  {
    id: "finish",
    num: "16",
    name: "Finish Work",
    short: "Finish",
    trade: "Multiple",
    duration: 12,
    contractor: "Harbor Interiors (GC)",
    lead: "S. Whitcomb",
    phone: "978-555-0815",
    areas: ["Drywall", "Tile (3 baths, kitchen backsplash)", "Flooring", "Millwork + paint", "Cabinets + counters"],
    milestones: [
      { label: "Drywall hang + finish", done: false },
      { label: "Prime + first coat", done: false },
      { label: "Tile + flooring", done: false },
      { label: "Cabinets + counters", done: false },
      { label: "Trim + final paint", done: false },
      { label: "Punch list", done: false },
      { label: "Final CO", done: false },
    ],
    notes: "Longest phase. Sub-scheduled by Harbor Interiors as GC.",
  },
];

// Contractor personas for "view as" tweak
window.PERSONAS = [
  { id: "owner",    label: "Owner (you)",         phase: null,         color: "#1a1a1a" },
  { id: "arch",     label: "Haskell + Co.",        phase: "eval",       color: "#6b7280" },
  { id: "demo",     label: "Coogan Demo",          phase: "demo",       color: "#6b7280" },
  { id: "framer",   label: "Mallon",               phase: "framing",    color: "#c9470a" },
  { id: "mason",    label: "TBD (Masonry)",        phase: "masonry",    color: "#6b7280" },
  { id: "roof",     label: "TBD (Roofing)",        phase: "roofing",    color: "#6b7280" },
  { id: "insul",    label: "AllJersey Spray Foam LLC", phase: "insulation", color: "#6b7280" },
  { id: "hvac",     label: "TBD (HVAC)",           phase: "hvac",      color: "#6b7280" },
  { id: "gas",      label: "Dalton Mechanical (Gas)",  phase: "gas",       color: "#6b7280" },
  { id: "elec",     label: "Voltage Bros.",        phase: "electric",   color: "#6b7280" },
  { id: "finish",   label: "Harbor Interiors",     phase: "finish",     color: "#6b7280" },
];

// Activity feed (most recent first)
window.ACTIVITY = [
  { when: "Today · 9:14a",   who: "J. Mallon",      phase: "framing",  text: "LVL beam set over kitchen. Ready for inspection Friday." },
  { when: "Today · 8:02a",   who: "You",            phase: null,       text: "Approved LVL spec change (14\" → 16\")." },
  { when: "Yesterday · 4:41p", who: "K. Dalton",    phase: "gas",      text: "Gas meter install scheduled w/ National Grid for Apr 28." },
  { when: "Yesterday · 2:10p", who: "TBD",           phase: "masonry",  text: "Site visit done. Front steps can overlap with framing wk 3." },
  { when: "Apr 14 · 11:30a",  who: "TBD",           phase: "roofing",  text: "Dumpster dropped. Tear-off pending dormer frame sign-off." },
  { when: "Apr 12 · 9:00a",   who: "R. Coogan",     phase: "demo",     text: "Demo complete. Sign-off walkthrough passed." },
];
